backend/product/urls.py
from django.urls import path

from backend.product import views as v

app_name = 'product'


urlpatterns = [
    path('', v.ProductListView.as_view(), name='product_list'),
    path('create/', v.product_create, name='product_create'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('accounts/', include('backend.accounts.urls')),  # without namespace
    path('ecommerce/', include('backend.ecommerce.urls', namespace='ecommerce')),
    path('product/', include('backend.product.urls', namespace='product')),
    path('admin/', admin.site.urls),
]

backend/product/models.py
from django.db import models
from django.urls import reverse


class Provider(models.Model):
    name = models.CharField('nome', max_length=30, unique=True)

    class Meta:
        verbose_name = 'fornecedor'
        verbose_name_plural = 'fornecedores'

    def __repr__(self):
        return f'Provider({self.name})'

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField('título', max_length=20, unique=True)
    price = models.DecimalField('preço', max_digits=7, decimal_places=2)
    manufacturing_date = models.DateField('data de fabricação', null=True, blank=True)  # noqa E501
    due_date = models.DateField('data de vencimento', null=True, blank=True)
    provider = models.ForeignKey(
        Provider,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("admin:product_product_change", args=(self.id,))

backend/product/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Product
        fields = ('title', 'price')

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/product/views.py
from django.shortcuts import render
from django.views.generic import ListView

from .forms import ProductForm
from .models import Product


class ProductListView(ListView):
    model = Product


def product_create(request):
    template_name = 'hx/product_form_hx.html'
    form = ProductForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            template_name = 'hx/product_result_hx.html'
            context = {'object': product}
            return render(request, template_name, context)

    context = {'form': form}
    return render(request, template_name, context)

backend/product/templates/product/product_list.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div class="row">
      <div class="col-auto">
        <h1>
          Lista de Produtos
          <a
            href=""
            class="btn btn-primary"
            data-toggle="modal"
            data-target="#addModal"
            hx-get="{% url 'product:product_create' %}"
            hx-target="#addContent"
            hx-swap="innerHTML"
          >Adicionar</a>
        </h1>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody id="productTbody">
        {% for object in object_list %}
          <tr>
            <td>{{ object.title }}</td>
            <td>R$ <span class="float-right">{{ object.price }}</span></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

  {% include "../includes/add_modal.html" %}

{% endblock content %}