backend/ecommerce/urls.py
from django.urls import path

from backend.ecommerce import views as v

app_name = 'ecommerce'

urlpatterns = [
    path('', v.OrderListView.as_view(), name='order_list'),
    path('create/', v.order_create, name='order_create'),
    path('add-row/', v.add_row_order_items_hx, name='add_row_order_items_hx'),
    path('product/price/', v.product_price, name='product_price'),
    path('product/filter_by_provider/', v.products_by_provider, name='products_by_provider'),
    path('<int:pk>/update/', v.order_update, name='order_update'),
    path('order-item/<int:pk>/delete/', v.order_item_delete, name='order_item_delete'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('accounts/', include('backend.accounts.urls')),  # without namespace
    path('ecommerce/', include('backend.ecommerce.urls', namespace='ecommerce')),
    path('product/', include('backend.product.urls', namespace='product')),
    path('admin/', admin.site.urls),
]

backend/ecommerce/models.py
from django.db import models

from backend.core.models import TimeStampedModel
from backend.product.models import Product, Provider


class Order(TimeStampedModel):
    nf = models.CharField('nota fiscal', max_length=7, unique=True)
    provider = models.ForeignKey(
        Provider,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'ordem de compra'
        verbose_name_plural = 'ordens de compra'

    def __str__(self):
        return self.nf

    def get_total(self):
        qs = self.order_items.filter(order=self.pk).values_list('price', 'quantity') or 0
        t = 0 if isinstance(qs, int) else sum(map(lambda q: q[0] * q[1], qs))
        return t


class OrderItems(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.SET_NULL,
        verbose_name='ordem',
        related_name='order_items',
        null=True,
        blank=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        verbose_name='produto',
        related_name='product_items',
        null=True,
        blank=True
    )
    quantity = models.PositiveIntegerField('quantidade')
    price = models.DecimalField('preço', max_digits=7, decimal_places=2)

    class Meta:
        ordering = ('pk',)
        verbose_name = 'ordem itens'
        verbose_name_plural = 'ordem itens'

    def __str__(self):
        return f'{self.pk} - {self.order.pk} - {self.product}'

    def get_subtotal(self):
        return self.price * (self.quantity or 0)

backend/ecommerce/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Order, OrderItems


class OrderForm(forms.ModelForm):
    required_css_class = 'required'

    nf = forms.IntegerField(label="Nota Fiscal")

    class Meta:
        model = Order
        fields = ('nf', 'provider')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['data-field'] = field_name


class OrderItemsForm(forms.ModelForm):
    required_css_class = 'required'

    id = forms.IntegerField()

    class Meta:
        model = OrderItems
        fields = ('order', 'id', 'product', 'quantity', 'price')

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['data-field'] = field_name

        self.fields['order'].label = ''
        self.fields['order'].widget = forms.HiddenInput()
        self.fields['order'].widget.attrs['data-field'] = 'order'

        self.fields['id'].label = ''
        self.fields['id'].widget = forms.HiddenInput()
        self.fields['id'].widget.attrs['data-field'] = 'id'

        self.fields['price'].widget.attrs['step'] = 0.01


OrderItemsFormset = inlineformset_factory(
    Order,
    OrderItems,
    form=OrderItemsForm,
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
)

backend/ecommerce/views.py
import json
import logging

from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView

from backend.product.models import Product, Provider

from .forms import OrderForm, OrderItemsForm, OrderItemsFormset
from .models import Order, OrderItems


class OrderListView(ListView):
    model = Order


def order_create(request):
    template_name = 'ecommerce/order_form.html'
    order_instance = Order()

    form = OrderForm(request.POST or None, instance=order_instance, prefix='main')
    formset = OrderItemsFormset(request.POST or None, instance=order_instance, prefix='items')

    lista = [f.fields for f in formset][0]  # dict_keys
    *formset_fields, = lista  # transforma dict_keys em lista

    if 'id' in formset_fields:
        formset_fields.remove('id')

    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('ecommerce:order_list')

    providers = Provider.objects.all()
    context = {
        'form': form,
        'formset': formset,
        'providers': providers,
        'formset_fields': json.dumps(formset_fields)
    }
    return render(request, template_name, context)


def add_row_order_items_hx(request):
    template_name = 'ecommerce/hx/row_order_items_hx.html'
    form = OrderItemsForm()

    products = Product.objects.all()
    try:
        provider = request.GET['main-provider']
        provider = int(provider)
        if provider:
            products = products.filter(provider__id=provider)
    except ValueError:
        logging.info('Valor inválido para main-provider')

    context = {'order_item_form': form, 'products': products}
    return render(request, template_name, context)


def products_by_provider(request):
    template_name = 'ecommerce/hx/products_select_hx.html'
    url = request.get_full_path()
    item = url.split('-')[1]
    provider_pk = list(request.GET.values())[0]
    products = Product.objects.filter(provider__id=provider_pk)

    context = {'products': products, 'item': item[0]}
    return render(request, template_name, context)


def product_price(request):
    template_name = 'ecommerce/hx/product_price_hx.html'
    url = request.get_full_path()
    item = url.split('-')[1]
    product_pk = list(request.GET.values())[0]
    product = Product.objects.get(pk=product_pk)

    context = {'product': product, 'item': item[0]}
    return render(request, template_name, context)


def order_update(request, pk):
    template_name = 'ecommerce/order_form.html'
    order_instance = Order.objects.get(pk=pk)

    form = OrderForm(request.POST or None, instance=order_instance, prefix='main')
    formset = OrderItemsFormset(request.POST or None, instance=order_instance, prefix='items')

    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('ecommerce:order_list')

    providers = Provider.objects.all()
    context = {'form': form, 'formset': formset, 'providers': providers}
    return render(request, template_name, context)


def order_item_delete(request, pk):
    order_item = OrderItems.objects.get(pk=pk)
    order_item.delete()
    return HttpResponse('')

backend/ecommerce/templates/ecommerce/order_form.html
<!-- order_form.html -->
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
    .legend {
      border-bottom: 1px solid #e5e5e5;
    }
  </style>

{% endblock css %}

{% block content %}

  <div class="row">
    <div class="cols">
      <form method="POST" novalidate>
        {% csrf_token %}

        <legend class="legend">Ordem de compra</legend>

        <div class="row">
          <div class="col-sm-12">

            <div class="form-inline">

              <label> {{ form.nf.label }} </label>
              {% render_field form.nf class="form-control" %}

              <label> {{ form.provider.label }} </label>
              <select id="main-provider" name="main-provider" class="form-control"
                hx-get="/ecommerce/product/filter_by_provider/"
                hx-target="[data-field=product]"
                hx-swap="outerHTML"
                onchange="setTimeout(() => {
                  filter_products();
                  reorderItems();
                  }, 500) "
              >
                <option value="0">----------</option>
                {% for provider in providers %}
                  {% if form.instance.provider == provider %}
                    <option value="{{ provider.pk }}" selected>{{ provider }} </option>
                  {% else %}
                    <option value="{{ provider.pk }}">{{ provider }}</option>
                  {% endif %}
                {% endfor %}
              </select>

            </div>

            {{ formset.management_form }}

          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">

            <legend class="legend">Itens</legend>

            <div id="order" class="form-inline">

              {% for order_item_form in formset %}
                <div id="item-{{ forloop.counter0 }}" class="form-group">
                  {% render_field order_item_form.order data-field="order" %}

                  {% render_field order_item_form.id data-field="id" %}

                  {{ order_item_form.product.label }}
                  {% render_field order_item_form.product class="form-control product" hx-get="/ecommerce/product/price/" hx-target="#id_items-0-price" hx-swap="outerHTML" %}

                  {{ order_item_form.quantity.label }}
                  {% render_field order_item_form.quantity class="form-control" %}

                  {{ order_item_form.price.label }}
                  {% render_field order_item_form.price class="form-control" %}

                  {% if order_item_form.id.value %}
                    <span
                      class="span-is-link no ml-2 remove-row"
                      hx-delete="{% url 'ecommerce:order_item_delete' order_item_form.id.value %}"
                      hx-confirm="Deseja mesmo deletar o item {{order_item_form.id.value}}?"
                      hx-target="#item-{{ forloop.counter0 }}"
                      hx-swap="outerHTML"
                    >
                      <i class="fa fa-times fa-lg"></i>
                    </span>
                  {% else %}
                    <span class="span-is-link no ml-2" onclick="removeRow()">
                      <i class="fa fa-times fa-lg"></i>
                    </span>
                  {% endif %}
                </div>
              {% endfor %}

            </div>

          </div>
        </div>

        <span
          id="addItem"
          class="btn btn-info mt-2"
          hx-get="{% url 'ecommerce:add_row_order_items_hx' %}"
          hx-target="#order"
          hx-swap="beforeend"
          hx-include="[name=main-provider]"
        >
          <i class="fa fa-plus"></i>
          Adicionar
        </span>

        <div class="row float-right">
          <div class="col-sm-12 mt-2">
            <div class="form-inline buttons">
              <button class="btn btn-primary" type="submit">
                <i class="fa fa-floppy-o"></i>
                Salvar
              </button>
              <a
                id="btn-close"
                href="{% url 'ecommerce:order_list' %}"
                class="btn btn-primary"
                style="display: none"
              >
                <i class="fa fa-close"></i>
                Fechar
              </a>
              <a
                href="{% url 'ecommerce:order_list' %}"
                class="btn btn-danger ml-2"
              >
                <i class="fa fa-times"></i>
                Cancelar
              </a>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>

{% endblock content %}

{% block js %}

  <script
    src="{% static 'js/main.js' %}"
    defer
    data-user="{{ request.user }}"
    data-buttonadd="#addItem"
    data-divitems="order"
    data-main="order"
    data-fields="{{ formset_fields }}"
  ></script>
  <!--
  divitems="order"                É o id dos campos do inlineform.
  main="order"                    É o nome do campo FK do model OrderItems, ou seja, order é FK para Order.
  fields="{{ formset_fields }}"   Lista com o nome dos campos do inlineform.
  -->

  <script>
    // Necessário por causa do delete
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });

    function filter_products(){
      first = document.querySelector('[data-field="product"]');
      if (first !== undefined){
        Array.from(document.querySelectorAll('[data-field="product"]'))
          .forEach((item, i) => {
          item.innerHTML = first.innerHTML
        });
      }

    }

  </script>

{% endblock js %}

backend/ecommerce/templates/ecommerce/order_list.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div class="row">
      <div class="col-auto">
        <h1>
          Ordens de Compra
          <a class="btn btn-primary" href="{% url 'ecommerce:order_create' %}">Adicionar</a>
        </h1>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Nota Fiscal</th>
          <th>Criado em</th>
          <th></th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody id="bookTbody">
        {% for object in object_list %}
          <tr class="bg-light">
            <td>{{ object }}</td>
            <td>{{ object.created|date:"d/m/Y H:i:s" }}</td>
            <td></td>
            <th>
              <a class="btn btn-success" href="{% url 'ecommerce:order_update' object.pk %}">
                <i class="fa fa-edit"></i> Editar
              </a>
            </th>
          </tr>
          <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Preço</th>
            <th>Subtotal</th>
          </tr>
          {% for items in object.order_items.all %}
            <tr>
              <td>{{ items.product.title }}</td>
              <td>{{ items.quantity }}</td>
              <td>R$ <span class="float-right">{{ items.price }}</span></td>
              <td>R$ <span class="float-right">{{ items.get_subtotal }}</span></td>
            </tr>
          {% endfor %}
          <tr>
            <td></td>
            <td></td>
            <th class="text-right">Total</th>
            <th>R$ <span class="float-right">{{ object.get_total }}</span></th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock content %}